version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    build: ./frontend/
    env_file: .env
    # кладём собранный фронт в общий том со статикой
    command: sh -c "cp -r /app/build/. /static/"
    volumes:
      - static:/static

  gateway:
    build: ./nginx/
    env_file: .env
    depends_on:
      - backend
    ports:
      - "9000:80"
    # nginx.conf ожидает /staticfiles и /app/media
    volumes:
      - static:/staticfiles
      - media:/app/media
