volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: dikalinkirill/kittygram_backend:latest
    platform: linux/amd64
    env_file: .env
    restart: always
    depends_on: [db]
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    image: dikalinkirill/kittygram_frontend:latest
    platform: linux/amd64
    env_file: .env
    command: sh -c "cp -r /app/build/. /frontend_static/"
    volumes:
      - static:/frontend_static

  gateway:
    image: dikalinkirill/kittygram_gateway:latest
    platform: linux/amd64
    env_file: .env
    restart: always
    depends_on: [backend]
    ports:
      - "80:80"
    volumes:
      - static:/staticfiles
      - media:/app/media
