name: Terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: Select the Terraform action
        required: true
        default: plan
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  tf:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Write SA key file
        run: echo "${{ secrets.YC_SA_JSON }}" > sa-key.json

      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
          TF_VAR_cloud_id:       ${{ secrets.YC_CLOUD_ID }}
          TF_VAR_folder_id:      ${{ secrets.YC_FOLDER_ID }}
          TF_VAR_tf_state_bucket:${{ secrets.TF_STATE_BUCKET }}
          TF_VAR_vm_ssh_user:    ${{ secrets.SSH_USER }}
          TF_VAR_vm_ssh_pubkey:  ${{ secrets.SSH_PUBLIC_KEY }}
        run: terraform init -input=false

      - name: Terraform Plan
        if: ${{ github.event.inputs.action == 'plan' }}
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
        run: terraform plan -input=false

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
        run: terraform apply -auto-approve -input=false

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
        run: terraform destroy -auto-approve -input=false
